---
version: "3.8"

networks:
  zabbix-network:
    driver: "bridge"

services:
  db:
    container_name: "mysql"
    image: "mysql:8.0.33"
    networks:
      - "zabbix-network"
    ports:
      - "3306:3306"
    volumes:
      - "./zabbix/mysql:/var/lib/data"
    environment:
      MYSQL_ROOT_PASSWORD: "123Mudar"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123Mudar"

  server:
    container_name: "zabbix-server"
    image: "zabbix/zabbix-server-mysql:alpine-6.0.3"
    networks:
      - "zabbix-network"
    links:
      - "db"
    restart: "always"
    ports:
      - "10051:10051"
    volumes:
      - "./zabbix/alertscripts:/usr/lib/zabbix/alertscripts"
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123Mudar"
    depends_on:
      - "db"

  frontend:
    container_name: "zabbix-frontend"
    image: "zabbix/zabbix-web-apache-mysql:alpine-6.0.3"
    networks:
      - "zabbix-network"
    links:
      - "db"
      - "server"
    restart: "always"
    ports:
      - "8081:8080"
      - "443:8443"
    environment:
      DB_SERVER_HOST: "mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123Mudar"
      PHP_TZ: "America/Sao_Paulo"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - "db"

  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    networks:
      - "zabbix-network"
    links:
      - "db"
      - "server"
    restart: "always"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app"
    depends_on:
      - "db"
      - "server"
...
